version: "3.9"
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      - PG_HOST=db
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
  db:
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spots
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./docker/spots.sql:/docker-entrypoint-initdb.d/spots.sql